Занятие 1: Основы JavaScript
js-tasks-ru/jsbasic-20210225_dkat0612 pull request #2
Opened 2021-03-03 19:16 UTC by dkat0612

2021-03-03 19:16 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2021-03-03 19:35 UTC, SinimaWath requested changes

2021-03-03 19:35 UTC, SinimaWath commented on 1-module/1-task/index.js
> +    result *= i;
В js практике, предпочитетельней такое написание:
```
for () {
  ...
}
```

2021-03-03 19:35 UTC, SinimaWath commented on 1-module/2-task/index.js
> +  return false;
Обычно малое количество правил(меньше 4), можно лаконично уместить в return:
`return name != null ....`

Это как раз тот случай

2021-03-03 19:35 UTC, SinimaWath commented on 1-module/3-task/index.js
> +    return "";
Эту проверку можно упростить до: 
```
if (!str) {
  return '';
}
```

2021-03-03 19:35 UTC, SinimaWath commented on 1-module/3-task/index.js
> +    return firstUCLetter;
Лишняя оптимизации сложения строк. Можно обойтись без этого условия

2021-03-03 19:35 UTC, SinimaWath commented on 1-module/3-task/index.js
> +  let firstUCLetter = str.slice(0, 1).toUpperCase();
Можно забрать через индекс.
`const firstUCLetter = str[0].toUpperCase()`

2021-03-03 19:35 UTC, SinimaWath commented on 1-module/4-task/index.js
> +  const SPAM_STRING_2 = "xxx";
Такие переменные-настройки. Принято уносить в глобальную область, нежели чем создавать их каждый раз в функции:
```
  const SPAM_STRING_1 = "1xbet";
  const SPAM_STRING_2 = "xxx";
  
function checkSpam(...


```

2021-03-03 19:35 UTC, SinimaWath commented on 1-module/4-task/index.js
> +  return false;
- Можно упростить до одной строчки: `return ..`
- проверка str != null, тут не нужна.

2021-03-03 19:35 UTC, SinimaWath commented on 1-module/5-task/index.js
> +  const CONTINUED = "…";
В глобальную область

2021-03-03 19:35 UTC, SinimaWath commented on 1-module/5-task/index.js
> +    return str;
По аналогии с другими замечаниями
```
if (!str || ) {
  ...
}
```

2021-03-04 08:48 UTC, SinimaWath requested changes

2021-03-04 08:48 UTC, SinimaWath commented on 1-module/3-task/index.js
> +    return "";
Не стоит опускать {}
```
if () {
  return '';
}
```

2021-03-04 08:48 UTC, SinimaWath commented on 1-module/5-task/index.js
> +    return str;
```
if () {
   ...
}
```

2021-03-04 11:00 UTC, SinimaWath approved these changes

2021-03-04 11:00 UTC, merged